---

  - name: "Download Velociraptor Client"
    ansible.builtin.get_url:
      url: "https://github.com/Velocidex/velociraptor/releases/download/{{ velociraptor_version }}/velociraptor-{{ velociraptor_version_patch }}-linux-amd64"
      dest: "~/velociraptor"
      mode: '0644'

  - name: Get Client Config
    ansible.builtin.copy:
      content: "{{ velociraptor_client_config }}"
      dest: "~/client.config.yaml"

  - name: Generate Client Installation Package
    ansible.builtin.shell: "~/velociraptor --config ~/client.config.yaml debian client --output ~/velociraptor_client.deb"
    args:
      creates: "~/velociraptor_client.deb"
    register: velociraptor_client_binary

  - name: Install Velociraptor Agent
    ansible.builtin.apt:
      deb: "~/velociraptor_client.deb"